apiVersion: apps/v1
kind: Deployment
metadata:
  name: cit270-fall2022-felipe
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cit270-fall2022-felipe
  template:
    metadata: 
      name: cit270-fall2022-felipe
      labels:
        app: cit270-fall2022-felipe
    spec:
      containers:
      - name: cit270-fall2022-felipe
        image: charphilip/cit270-fall2022 #add this line
        volumeMounts:
        - name: ssl
          mountPath: "/usr/src/app/SSL"
        command: ["npm"]
        args: ["run", "start"]
        resources:
          requests:
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
        imagePullPolicy: Always
      volumes:
      - name: ssl
        secret: 
          secretName: ssl.secret.felipep
---
apiVersion: v1
kind: Service
metadata:
  name: cit270-fall2022-felipe-loadbalancer
spec:
  selector:
    app: cit270-fall2022-felipe
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 443
  